pipeline {
    agent any
    environment {
        registry = 'pavangandham/dockerpipeline'
        registryCredential = 'dockerhub_id'
        dockerSwarmManager = '10.40.1.201:2375'
        dockerHost = '10.40.1.201'
        dockerImage = ''
    }
    stages {
        stage('Cloning our Git') {
            steps {
                git 'https://github.com/mavrick202/dockertest1.git'
            }
        }
        stage('Building our image') {
            steps {
                script {
                    dockerImage = docker.build registry + ":v$BUILD_NUMBER"
                }
            }
        }
        stage('Push Image To DockerHUB') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Cleaning up') {
            steps {
                sh "docker rmi $registry:v$BUILD_NUMBER"
            }
        }
        stage('Deploying to Docker Swarm') {
            steps {
                sh "docker -H tcp://$dockerSwarmManager service rm testing1 || true"
                sh "docker -H tcp://$dockerSwarmManager service create --name testing1 -p 8100:80 $registry:v$BUILD_NUMBER"
            }
        }
        stage('Verifying the Deployment') {
            steps {
                sh "curl http://$dockerHost:8100 || exit 1"
            }
        }
    }
}
